const reviews = [
  {
    id: 1,
    name: "Bettina Bergeon",
    job: "Structural Engineer",
    image: "https://robohash.org/sedisteofficia.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 2,
    name: "Salomi Goward",
    job: "Environmental Specialist",
    image:
      "https://robohash.org/consequaturvoluptasexcepturi.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 3,
    name: "Zared Gerrard",
    job: "Sales Associate",
    image: "https://robohash.org/etperspiciatisducimus.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 4,
    name: "Zea Hurworth",
    job: "Environmental Tech",
    image: "https://robohash.org/remquiaomnis.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 5,
    name: "Ludvig Hugill",
    job: "Operator",
    image:
      "https://robohash.org/suscipitreiciendislaudantium.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 6,
    name: "Cristen Serle",
    job: "Systems Administrator III",
    image:
      "https://robohash.org/voluptatemfugiatlaborum.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 7,
    name: "Rafael Hunston",
    job: "Graphic Designer",
    image: "https://robohash.org/pariaturautemea.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 8,
    name: "Charmaine Rudall",
    job: "Information Systems Manager",
    image: "https://robohash.org/similiqueminimaharum.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 9,
    name: "Bari Alleburton",
    job: "Web Developer III",
    image: "https://robohash.org/doloresvoluptatumsit.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 10,
    name: "Dale Packer",
    job: "Dental Hygienist",
    image: "https://robohash.org/natusenimratione.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 11,
    name: "Robbie Squelch",
    job: "Analog Circuit Design manager",
    image: "https://robohash.org/solutalaboredolorem.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 12,
    name: "Joshua Halwood",
    job: "Internal Auditor",
    image: "https://robohash.org/quireprehenderitquia.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 13,
    name: "Reuben Peeters",
    job: "Financial Analyst",
    image:
      "https://robohash.org/voluptatemlaudantiumarchitecto.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 14,
    name: "Free Ferrea",
    job: "Developer I",
    image:
      "https://robohash.org/nesciuntnihilcupiditate.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 15,
    name: "Heda Eager",
    job: "Research Associate",
    image: "https://robohash.org/magnivelitquia.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 16,
    name: "Daffy Cattach",
    job: "Analog Circuit Design manager",
    image: "https://robohash.org/temporeafugiat.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 17,
    name: "Sally Grinikhin",
    job: "Geologist IV",
    image: "https://robohash.org/quiuteveniet.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 18,
    name: "Durant Dalligan",
    job: "Internal Auditor",
    image: "https://robohash.org/quicumab.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 19,
    name: "Augusto Truscott",
    job: "Help Desk Operator",
    image: "https://robohash.org/eaquaeratquo.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 20,
    name: "Dee dee Penke",
    job: "Staff Accountant I",
    image: "https://robohash.org/utoditesse.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 21,
    name: "Colline Cortez",
    job: "Senior Developer",
    image: "https://robohash.org/inconsequatursit.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 22,
    name: "Boonie Readshaw",
    job: "Senior Cost Accountant",
    image:
      "https://robohash.org/doloresdebitisvoluptas.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 23,
    name: "Tallulah Pickett",
    job: "Help Desk Operator",
    image: "https://robohash.org/consequunturabea.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 24,
    name: "Pen Groger",
    job: "Administrative Officer",
    image: "https://robohash.org/voluptatemeosqui.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 25,
    name: "Dayle Buncom",
    job: "Office Assistant III",
    image: "https://robohash.org/expeditaestipsa.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 26,
    name: "Richart Meighan",
    job: "VP Sales",
    image: "https://robohash.org/eumaspernaturut.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 27,
    name: "Alyosha Persey",
    job: "Speech Pathologist",
    image: "https://robohash.org/dolornostrumcorporis.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 28,
    name: "Freddy Jaeggi",
    job: "Nuclear Power Engineer",
    image: "https://robohash.org/esseutqui.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 29,
    name: "Ancell Crighten",
    job: "Information Systems Manager",
    image: "https://robohash.org/etducimusrerum.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 30,
    name: "Tommie Scotter",
    job: "Programmer Analyst I",
    image:
      "https://robohash.org/molestiaeaccusantiumillum.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 31,
    name: "Cross Giorgiutti",
    job: "Assistant Professor",
    image: "https://robohash.org/eaautemsed.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 32,
    name: "Olag Hinchcliffe",
    job: "Teacher",
    image:
      "https://robohash.org/occaecatiexplicabodolore.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 33,
    name: "Edita Dengate",
    job: "Quality Control Specialist",
    image: "https://robohash.org/suscipitquovoluptas.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 34,
    name: "Johnette Reddan",
    job: "Geologist III",
    image: "https://robohash.org/utrecusandaeminus.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 35,
    name: "Shayna Bettesworth",
    job: "Payment Adjustment Coordinator",
    image: "https://robohash.org/doloretaut.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 36,
    name: "Phylis Gowler",
    job: "Occupational Therapist",
    image:
      "https://robohash.org/recusandaeexplicaboimpedit.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 37,
    name: "Gordon Delgardo",
    job: "Dental Hygienist",
    image: "https://robohash.org/officiaeosanimi.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 38,
    name: "Theodor Shorrock",
    job: "Senior Cost Accountant",
    image: "https://robohash.org/autsuntminus.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 39,
    name: "Maressa Audenis",
    job: "Human Resources Manager",
    image: "https://robohash.org/voluptasfugitiusto.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 40,
    name: "Jasmine Kirkbright",
    job: "Nurse",
    image:
      "https://robohash.org/voluptatumdolorrepudiandae.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 41,
    name: "Leopold Grisard",
    job: "Senior Editor",
    image:
      "https://robohash.org/dignissimosexercitationemautem.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 42,
    name: "Haywood Chancellor",
    job: "Payment Adjustment Coordinator",
    image: "https://robohash.org/sequidoloremsint.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 43,
    name: "Penelope Norssister",
    job: "Registered Nurse",
    image: "https://robohash.org/autaccusantiumnam.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 44,
    name: "Demeter Blay",
    job: "VP Marketing",
    image: "https://robohash.org/nonestnon.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 45,
    name: "Cecilio Algy",
    job: "Structural Engineer",
    image: "https://robohash.org/laboriosameumdicta.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 46,
    name: "Lynnette Warlock",
    job: "Software Engineer II",
    image:
      "https://robohash.org/autemexercitationemsit.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 47,
    name: "Reidar Lote",
    job: "Speech Pathologist",
    image: "https://robohash.org/etutvelit.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 48,
    name: "Gena Dunthorn",
    job: "Safety Technician IV",
    image: "https://robohash.org/doloreseaquesint.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 49,
    name: "Arabele Jakes",
    job: "Nurse",
    image: "https://robohash.org/occaecatiillorerum.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
  {
    id: 50,
    name: "Eadmund Mauchlen",
    job: "VP Sales",
    image: "https://robohash.org/temporapossimusut.png?size=50x50&set=set1",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa               animi necessitatibus hic velit! A neque eos quas, harum recusandae               id.",
  },
];

export default reviews;
